wandb_version: 1

path:
  desc: null
  value: genres_mod.parquet
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715854359
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
