name: exercise_3
channels:
  - conda-forge
     - requests=2.24.0
     - pip=20.3.3
     - mlflow=1.14.1
     - hydra-core=1.0.6
     - pip=20.3.3
     - pip:
        - wandb==0.10.21
  - defaults
dependencies:
  # Complete HERE
