name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - notebook
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling
  - pyarrow
  - pip:
      - wandb