wandb_version: 1

path:
  desc: null
  value: wandb_test
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715102774.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
